### ISSUE TITLE
Urinal Height from Ground

### ISSUE THREAD

**Issue by icirellik** [devshorts/urinal#4] opened 2016-12-16 23:28 UTC
Tall people have a hard time and must avoid them at all cost.

**Comment by devshorts** [comment] 2016-12-17 02:23
Good idea, short people may prefer the smaller one too

**Comment by jakeswenson** [comment] 2017-01-05 01:32
This is a duplicate of #2
It isn't directly related to height, its more of a DTF measurement. https://youtu.be/mMeqEDEfniA?t=1m12s

**Comment by devshorts** [comment] 2017-01-05 01:34
I interpreted #2 as from the urinal bottom (i.e. the hole) to the pee source, and not the urinal bottom to the ground. So one is distance of stream and one is distance to pee source (height of urinator).  Slightly different, unless I'm misinterpreting the suggestion @jakeswenson 

To illustrate I've created this infographic:

![image](https://cloud.githubusercontent.com/assets/1799346/21666093/7f8e0ee8-d2a4-11e6-9d30-fbcbf07dfdf7.png)

**Comment by jakeswenson** [comment] 2017-01-05 01:37
varying the height of the urinal to the floor directly varies the distance from the pee source to the urinal, no? if you account for #2 you naturally account for this issue. Unless i'm misunderstanding. Please see cited SV episode for technical details

**Comment by devshorts** [comment] 2017-01-05 01:38
Fair, but the difference differences have different side effects that may be weighted differently by user.  I think this topic might need more discussion

**Comment by jakeswenson** [comment] 2017-01-05 01:41
Thanks for your infographic, but it's not clear to me where the pee source is. Can you please update that graphic to accurately reflect the situation.

**Comment by jakeswenson** [comment] 2017-01-05 01:43
I showed this to @bspradling8 and he asked "Why is the urinal on the ceiling?"

**Closed as completed** 2017-03-23 14:23 UTC
Labels: enhancement
